source 'http://rubygems.org'
gem 'cucumber', '~>2.2.0'
gem 'rspec'
gem 'ffi'
gem 'watir'
gem 'watir-webdriver', '~>0.9.9'
gem 'selenium-webdriver'
gem 'headless'
gem 'titleize'
gem 'json'
gem 'gherkin'
gem 'syntax'
gem 'rake'
gem 'page-object'
gem 'require_all'
gem 'fig_newton'
gem 'data_magic'